name: it_support
description: A new Flutter project for IT support tickets.

publish_to: 'none' # Remove esta linha se você quiser publicar para o pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Para garantir que está usando o Flutter Lints
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

